use_frameworks!

platform :ios, '13.0'

target 'Feature_Example' do
  pod 'Feature', :path => '../'

  target 'Feature_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'iOSSnapshotTestCase'
    pod 'Nimble-Snapshots'

    pod 'Feature', :path => '../', :testspecs => ['Tests']
  end
end
